---
# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
  - init: |
      mkdir -p ~/.ssh && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      eval `ssh-agent -s`
      ssh-add ~/.ssh/id_rsa
      alias kamal='docker run -it --rm -v "${PWD}:/workdir" -v "${SSH_AUTH_SOCK}:/ssh-agent" -v /var/run/docker.sock:/var/run/docker.sock -e "SSH_AUTH_SOCK=/ssh-agent" ghcr.io/basecamp/kamal:latest'
      npm install
    command: npm run dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Astro Dev Server
    description: open Astro Dev Server at port 4321
    port: 4321
    onOpen: open-browser
  - name: Astro Container Test Server
    description: open Astro Dev Server at port 4322
    port: 4322
    onOpen: open-browser

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - github.vscode-github-actions
    - astro-build.houston
    - vscode-icons-team.vscode-icons
    - ms-azuretools.vscode-docker
